[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    'openzeppelin-contracts-06/=lib/openzeppelin-contracts-v3.4.0/contracts/',
    'openzeppelin-contracts-08/=lib/openzeppelin-contracts-v4.9.0/contracts/',
    '@openzeppelin-v3/=lib/openzeppelin-contracts-v3.3.0/contracts/',
    '@openzeppelin/=lib/openzeppelin-contracts-v4.9.0/contracts/',
]
rpc_endpoints = { sepolia = "https://rpc.ankr.com/eth_sepolia" }
#eth_rpc_url = "https://rpc.ankr.com/eth_sepolia"
