[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@openzeppelin-v3/=lib/openzeppelin-contracts-v3.3.0/contracts/',
    '@openzeppelin/=lib/openzeppelin-contracts/contracts/',
]
rpc_endpoints = { sepolia = "https://rpc.ankr.com/eth_sepolia" }
